#ワークフロー名
name: leaflet_API
on:
  #push:
  workflow_dispatch:
  schedule:
  #7:00起動
   - cron: '0 22 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      #リポジトリからチェックアウトして以下の処理を実行していく
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install bs4
          pip install Pillow
          
      - name: Run script
        env:
          LEAFLET_MANAGEMENT_URL: ${{ secrets.LEAFLET_MANAGEMENT_URL }}
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: |
          python leaflet_API.py
